# Site settings
title: blog.csec
description: Just a bunch of computer science students trying to make their way in the big bad world of CS.

baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://csec.nith.ac.in" # the base hostname & protocol for your site

future: true

authors:
  disqus: csec-nith-ac-in-blog
  param:
    fullname: Param Singh
    github: paramsingh
    twitter: paramsingh258
  shikhar:
    fullname: Shikhar Srivastava
    github: shikharsrivastava
  rohan:
    fullname: Rohan Jaswal
    github: rohanjaswal2507
  ferbncode:
    fullname: Suyash Garg
    github: suyashgargsfam
  rahul:
    fullname: Rahul Raturi
    github: rahul-raturi
  udit:
    fullname: Udit Gulati
    github: uditgulati


# google_analytics: 'UA-XXXXXXXX-X'

# Syntax highlighting
highlightstyle: ''
styles: [agate, androidstudio, arta, asceti, atelier-cave.dark, atelier-cave.light, atelier-dune.dark, atelier-dune.light, atelier-estuary.dark, atelier-estuary.light, atelier-forest.dark, atelier-forest.light, atelier-heath.dark, atelier-heath.light, atelier-lakeside.dark, atelier-lakeside.light, atelier-plateau.dark, atelier-plateau.light, atelier-savanna.dark, atelier-savanna.light, atelier-seaside.dark, atelier-seaside.light, atelier-sulphurpool.dark, atelier-sulphurpool.light, brown_paper, codepen-embed, color-brewer, dark, darkula, default, docco, far, foundation, github, github-gist, googlecode, grayscale, hopscotch, hybrid, idea, ir_black, kimbie.dark, kimbie.light, magula, mono-blue, monokai, monokai_sublime, obsidian, paraiso.dark, paraiso.light, pojoaque, railscast, rainbow, school_book, solarized_dark, solarized_light, styles_list.txt, sunburst, tomorrow, tomorrow-night-blue, tomorrow-night-bright, tomorrow-night, tomorrow-night-eightie, v, xcode, zenburn]

# Handling Reading
exclude: ["README.md", "README.html"]

# Build settings
highlighter: null
markdown: kramdown
